import React, { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import { Volume2, Square, Share2, Check } from 'lucide-react';

export default function HandoverNarrative({ reportMarkdown, shiftId, variancePercent }) {
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [copied, setCopied] = useState(false);

  const defaultSummary = `Shift ${shiftId || 'SH-402'} concluded with a production variance of ${variancePercent || '-15.5'}%. All calculated KPIs and Z-score sensor anomalies have been verified against operational standards.`;

  const rawText = reportMarkdown ? reportMarkdown.replace(/[*_`#]/g, '') : defaultSummary;

  useEffect(() => {
    return () => {
      if (window.speechSynthesis) {
        window.speechSynthesis.cancel();
      }
    };
  }, []);

  const handlePlayVoice = () => {
    if (!('speechSynthesis' in window)) {
      alert("Speech synthesis is not supported on this browser.");
      return;
    }

    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      return;
    }

    window.speechSynthesis.cancel(); // Stop any active speech
    const utterance = new SpeechSynthesisUtterance(rawText);
    utterance.rate = 1.0;
    utterance.pitch = 1.0;

    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);

    setIsSpeaking(true);
    window.speechSynthesis.speak(utterance);
  };

  const handleCopyTeamsSlack = () => {
    const formattedMarkdown = `🚨 *LogIQ Shift Handover Briefing — Shift ${shiftId || 'SH-402'}*\n*Production Variance*: \`${variancePercent || '-15.5'}%\` \n----------------------------------------\n${reportMarkdown || defaultSummary}\n----------------------------------------\n*Generated by LogIQ Operational Command Center*`;

    navigator.clipboard.writeText(formattedMarkdown).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }).catch(err => {
      console.error("Clipboard copy failed:", err);
    });
  };

  return (
    <div className="industrial-card">
      <div className="card-title">
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <span>1. EXECUTIVE SHIFT SUMMARY</span>
          <span className="badge badge-info" style={{ fontSize: '0.65rem' }}>VERIFIED FACT-BASED NARRATIVE</span>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }} className="no-print">
          {/* Voice Briefing Button */}
          <button
            onClick={handlePlayVoice}
            className={`btn ${isSpeaking ? 'btn-secondary' : 'btn-secondary'}`}
            style={{
              fontSize: '0.725rem',
              padding: '0.3rem 0.6rem',
              background: isSpeaking ? 'rgba(220, 38, 38, 0.15)' : undefined,
              borderColor: isSpeaking ? '#DC2626' : undefined,
              color: isSpeaking ? '#F87171' : undefined
            }}
            title={isSpeaking ? "Stop Voice Briefing" : "Listen to Audio Shift Briefing"}
          >
            {isSpeaking ? <Square size={13} color="#F87171" /> : <Volume2 size={13} color="var(--accent-blue)" />}
            <span>{isSpeaking ? 'Stop Audio' : 'Play Voice Briefing'}</span>
          </button>

          {/* Copy for Teams / Slack Button */}
          <button
            onClick={handleCopyTeamsSlack}
            className="btn btn-secondary"
            style={{ fontSize: '0.725rem', padding: '0.3rem 0.6rem' }}
            title="Copy formatted shift narrative for MS Teams / Slack"
          >
            {copied ? <Check size={13} color="var(--status-success)" /> : <Share2 size={13} />}
            <span>{copied ? 'Copied to Clipboard!' : 'Copy for Teams/Slack'}</span>
          </button>
        </div>
      </div>

      <div style={{ fontSize: '0.85rem', color: 'var(--text-primary)', lineHeight: 1.6 }}>
        {reportMarkdown ? (
          <div className="markdown-container">
            <ReactMarkdown>{reportMarkdown}</ReactMarkdown>
          </div>
        ) : (
          <p>{defaultSummary}</p>
        )}
      </div>
    </div>
  );
}

